### ISSUE TITLE
Question/Help

### ISSUE THREAD

**Issue by PlainJane20** [whizzzkid/python-threaded-mailer#1]
great work @whizzzkid aka Nishant! Could you advise or help with a code on how we can eliminate pulling duplicate emails and group them by conversation when extracting (lets say gmail) and also how can we pull counts of those ex: in a thread if we had 4 total count to pull 4? thanks much

**Comment by whizzzkid** [comment]
@PlainJane20 I am missing the context in regards to this. I think you can modify the SQL to not pull in duplicates. You can also have a SQL query to group the emails however you like them. I would appreciate more context.
